### ISSUE TITLE
Change the App Name

### ISSUE THREAD

**Issue by adiadil** [polymorphicshade/NewPipe#156] opened 2022-03-16 16:03 UTC
Change the name from 'NewPipe SponsorBlock' to 'NewPipe X'

the current name is very long, I think the name 'NewPipe X' is very apt.

**Comment by Atemu** [comment] 2022-03-16 16:30
Duplicate of https://github.com/polymorphicshade/NewPipe/issues/12

**Closed** 2022-03-17 05:33 UTC
