### ISSUE TITLE
Can't install latest version "App not installed"

### ISSUE THREAD

**Issue by KuromeSan** [polymorphicshade/NewPipe#131] opened 2022-02-02 19:51 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [X ] This issue CANNOT be reproduced with the same version of upstream NewPipe 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Download the latest apk.
Try install it

### Actual behavior
"App not installed" error previous version does work

### Expected behavior
Click install and it installs

### Device info

 - Android version/Custom ROM version: 10 QKQ1Q1.191014.001
 - Device model: Redmi 8A

**Comment by MDP43140** [comment] 2022-02-03 07:59
this might be caused by wrong certificate, you can try to backup the configuration by opening NewPipe > Settings > Content > Export database.
after that, you can uninstall current version, and reinstall new version.
then you can restore all the settings by opening NewPipe, then Settings > Content > Import database.

**Comment by Isssuemaker** [comment] 2022-02-25 05:49
If your bug solved than close the issue

**Closed** 2022-03-21 23:36 UTC
Labels: bug
