### ISSUE TITLE
Cierre inesperado

### ISSUE THREAD

**Issue by ByronScubides** [polymorphicshade/NewPipe#256] opened 2022-10-09 05:02 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24

### Steps to reproduce the bug

1. Reproducir canción
2. Pauso y reproduzco desde auriculares inalámbricos
3. Cierre inesperado
4. Aviso de informe de error

### Screenshots/Screen recordings

<img alt="Screenshot_2022-10-08-23-59-30-720_org polymorphicshade newpipe" src="https://user-images.githubusercontent.com/115387704/194738861-fde71b3a-2b3c-45bd-8db2-9647baefdf8a.jpg" height=600 />

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=Q7JBMr_LYGU
* __Content Country:__ US
* __Content Language:__ es-US
* __App Language:__ es_US
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(136, null, null, video/avc, avc1.64001F, 303092, null, [720, 720, 25.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.AVC
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
	... 5 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 (MIUI Global 12.5.8 Estable

### Affected device model

Redmi note 8 pro 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=Q7JBMr_LYGU
* __Content Country:__ US
* __Content Language:__ es-US
* __App Language:__ es_US
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(136, null, null, video/avc, avc1.64001F, 303092, null, [720, 720, 25.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.AVC
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
	... 5 more

```
</details>
<hr>

**Comment by Atemu** [comment] 2022-10-09 13:43
That looks like an issue with Exoplayer and/or your phone's decoding system.

Is this reproducible? Is this not reproducible in Upstream NewPipe?

**Comment by NameLessGO** [comment] 2022-10-17 04:01
> Is this reproducible? Is this not reproducible in Upstream NewPipe?

Having the same problem here, the only difference was mine Linux version was 12-31

There are 2 instances in which the app closes
1.  Unfortunately couldn't figure out this one, but goes like this, you are watching your video with sponsorblock integration on, then an error displays shows up, the warning that comes when the app stops working (aka freezes), if you click continue nothing happens, and you can resume your video, the reason why im saying this, its because it might be related to the second problem since they came a week ago~.

2. If you put a video on background, either by the display going off on it own or using the background mode (in this case the app must be closed for the newpipe to break)

Thought it was happening because of the release for Android 13 in the S21 which is coming up in the end of this month, maybe some micro updates to prepare the system, but just speculations

**Comment by NameLessGO** [comment] 2022-11-01 15:52
Fixed by reinstalling the newest version, my guess would be that the auto updater feature messed with it, idk

**Closed** 2023-04-10 00:26 UTC
Labels: bug
