### ISSUE TITLE
Download bug

### ISSUE THREAD

**Issue by Fehertukor** [polymorphicshade/NewPipe#35] opened 2021-02-20 18:39 UTC
In the latest 2 builds the downloading option does not work for me.
I have returned to 0.20.8 and everything works.
Is it this build problem build or is it official build bug?

**Comment by multichoyce** [comment] 2021-02-20 21:58
@Fehertukor you can install the official app alongside this one, they won't overwrite each other. 

Tested and yeah it worked on the official but not on this fork

**Comment by polymorphicshade** [comment] 2021-02-21 05:30
I found a fix for this. It will be in the next revision coming up soon.

**Comment by polymorphicshade** [comment] 2021-02-21 06:53
@Fehertukor @multichoyce give this [APK](https://github.com/polymorphicshade/NewPipe/files/6017299/newpipe_x_sponsorblock_debug.zip) a shot and let me know if you are still having issues.

**Comment by Fehertukor** [comment] 2021-02-21 14:46
@polymorphicshade thanks for your work, sadly this version crashing the app when i try to download.

**Comment by polymorphicshade** [comment] 2021-02-21 16:02
@Fehertukor can you post the crash message and possibly the stack trace? Also you may have to uninstall the older version, not entirely sure though.

**Comment by multichoyce** [comment] 2021-02-21 21:21
@polymorphicshade this is working fine on my end, yet to give a go on the other one

**Comment by polymorphicshade** [comment] 2021-02-21 21:23
@multichoyce sorry I'm a bit confused... do you mean that the debug APK I posted above seems to have fixed the issue?

**Comment by multichoyce** [comment] 2021-02-21 21:26
@polymorphicshade yeah, sorry for the confusion. I meant the issue reported here is fixed with the debug apk posted here, no need for the workaround download option working as intended

**Comment by polymorphicshade** [comment] 2021-02-21 21:32
@multichoyce oh awesome!

**Comment by polymorphicshade** [comment] 2021-02-21 22:17
This should now be fixed in the latest release.

**Closed by polymorphicshade** 2021-02-21 22:17 UTC
