### ISSUE TITLE
20 video search limit

### ISSUE THREAD

**Issue by bingoxo** [polymorphicshade/NewPipe#19] opened 2020-12-24 02:29 UTC
I am on latest version , i get exactly 20 videos in search everytime , i just cleared the app data and i'm still getting same the same issue

**Comment by polymorphicshade** [comment] 2020-12-24 17:50
I cannot reproduce this on either vanilla NewPipe or NewPipe x SponsorBlock.
@bingoxo what search term(s) are you using?

**Comment by bingoxo** [comment] 2020-12-24 17:57
Whatever i search for i always get exactly 20 searches i just retested now , and just installed vanilla newpipe and i al having same issue , do note that i don't have google play services installed and i'm on grapheneos  .

Just tested again with another phone and no issues at all

**Comment by polymorphicshade** [comment] 2020-12-24 18:27
@bingoxo hm... if you say this also happens on vanilla NewPipe, then I'm going to close this issue since this doesn't seem related to my fork. It might be worth submitting an issue on NewPipe's official Github repo instead of mine.

**Closed by polymorphicshade** 2020-12-24 18:27 UTC
Labels: bug
