### ISSUE TITLE
Rename this project to NewPipe Vanced

### ISSUE THREAD

**Issue by AdyaGD** [polymorphicshade/NewPipe#163] opened 2022-03-20 14:43 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

literally just rename the app to NewPipe Vanced

### Why do you want this feature?

as a tribute to our fallen solider, yt vanced 

### Why ist the feature relevant to this fork?

since people want RYD integration to this fork, why not just make this repo about additional NewPipe features?

**Comment by cyberofficial** [comment] 2022-03-20 15:36
And then YouTube's legal team Comes after this project next

**Comment by Atemu** [comment] 2022-03-21 01:31
Youtube holds no trademarks on "Vanced" that I know of.

Duplicate of #12.

**Comment by Mesum-Hussain** [comment] 2022-03-21 06:50
Dumbest idea!

**Comment by polymorphicshade** [comment] 2022-03-21 23:15
Closed, see [here](https://github.com/polymorphicshade/NewPipe/discussions/164).

**Closed by polymorphicshade** 2022-03-21 23:15 UTC
Labels: enhancement

**Comment by DraconicNEO** [comment] 2022-04-07 04:16
Just seems scammy and uncool, like trying to convince people that this is Vanced when it isn't actually anything like vanced.
