### ISSUE TITLE
Better handling of suspended/deleted channels

### ISSUE THREAD

**Issue by kakolisgay** [polymorphicshade/NewPipe#27] opened 2021-01-23 04:00 UTC
[Upstream Issue](https://github.com/TeamNewPipe/NewPipe/issues/3313)

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Currently Newpipe handles suspended and deleted accounts by simply throwing an exception. To normal users, this doesn't make it obvious what's happened or why something failed. For users with large lists of subscriptions, this makes it tedious to get the error to go away

Newpipe should instead provide some sort of UI hint to signal to the user that a channel is no longer accessible. Perhaps in the "Subscriptions" dropdown?

#### Is your feature request related to a problem? Please describe it

Yes. YouTube (and PeerTube) will throw an exception if a channel is deleted or suspended.

#### How will you/everyone benefit from this feature?

This is mostly a QoL change

**Comment by polymorphicshade** [comment] 2021-01-24 00:28
Seems like a good change. Can you provide me a search term or something I can use to reproduce this?

**Comment by kakolisgay** [comment] 2021-01-24 03:21
I think you could add a few suspended accounts for testing by exporting, editing, and reimporting a newpipe backup. [AltCensored](https://altcensored.com) lists a lot of accounts you can use for testing

**Comment by polymorphicshade** [comment] 2021-01-27 00:52
@kakolisgay I've tried exporting a subscription list, editing the channel, and re-importing it. I got no exceptions and the import automatically ignored the terminated channel. Can you post the exception message and stacktrace?

**Comment by kakolisgay** [comment] 2021-01-30 15:14
* __User Action:__ requested feed
* __Request:__ Loading feed
```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UCPWXIOPK-9myzek6jHR5yrg
at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:225)
at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:67)
at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:114)
at io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeFeedExtractor.getId(YoutubeFeedExtractor.java:55)
at org.schabi.newpipe.extractor.feed.FeedInfo.getInfo(FeedInfo.java:39)
at org.schabi.newpipe.util.ExtractorHelper.lambda$getFeedInfoFallbackToChannelInfo$6(ExtractorHelper.java:155)
at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$ep3f-iOI31R0rCiVMC3iRDaEOxw.call(Unknown Source:4)
at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
at io.reactivex.rxjava3.internal.operators.maybe.MaybeSwitchIfEmptySingle.subscribeActual(MaybeSwitchIfEmptySingle.java:45)
at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:215)
... 11 more
```

**Comment by polymorphicshade** [comment] 2021-01-31 03:54
Oh I see. Looking in to this it seems this is a known issue and I believe the NewPipe devs are working on it (since there seems to be similar issues submitted on their repo). Looks like this issue stems from their extractor (a separate repository I did not fork).

Also it seems their error-handling for external calls to the extractor is by design - modifying the UI to handle this "better" or "cleaner" would be a significant change, so I'd rather wait for the NewPipe devs to fix their extractor code.

Gonna close this for now, unless this issue gets out of hand.

**Closed by polymorphicshade** 2021-01-31 03:54 UTC
Labels: enhancement
