### ISSUE TITLE
Rename app to "NewPipe X"

### ISSUE THREAD

**Issue by brunodoin** [polymorphicshade/NewPipe#221] opened 2022-08-05 17:01 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I think the app should have a shorter name instead of "NewPipe SponsorBlock". My suggestion is "NewPipe X"

### Why do you want this feature?

Not only the current name ignores the extra option of returning dislikes, but it also makes the app drawer look cluttered.

### Why ist the feature relevant to this fork?

Honestly there are no reasons to change the name other than simplicity and maybe branding.

### Additional information

While we're at it, why not change the icon as well? I've sketched something on GIMP to give an idea of how it could be (sorry about the size).
![icon_suggestion](https://user-images.githubusercontent.com/58440886/183125543-9e642d30-fd86-4a11-b48e-54fd0113052e.png)

**Comment by Atemu** [comment] 2022-08-05 17:03
Dupe of https://github.com/polymorphicshade/NewPipe/issues/12

**Closed** 2022-08-28 22:59 UTC
Labels: enhancement
