### ISSUE TITLE
Sponsorblock doesn't work on popup

### ISSUE THREAD

**Issue by jaksjaaj** [polymorphicshade/NewPipe#21] opened 2020-12-26 09:16 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by polymorphicshade** [comment] 2020-12-27 01:12
I can't reproduce this on my device or emulators...

Are you sure you have SponsorBlock enabled?
Which video were you watching?

Also it looks like you quickly copied and pasted the template without filling it all in. I don't really care all that much, but it would help to include a little bit more information.

**Comment by polymorphicshade** [comment] 2021-01-20 00:54
I'm going to close this since nobody else has chimed in and I cannot reproduce it. I'll reopen if someone else experiences the same issue.

**Closed by polymorphicshade** 2021-01-20 00:54 UTC
Labels: bug
