### ISSUE TITLE
Videos and content not loading

### ISSUE THREAD

**Issue by Reggie2561** [polymorphicshade/NewPipe#227] opened 2022-08-12 18:34 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [ ] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest SponserBlock

### Steps to reproduce the bug

1. Open the app
2. App doesnt load content
3. Restart wifi it works for a little
4. Problem occures again out of nowhere
5. Repeat from step 3

### Expected behavior

When wifi is restarted it should display trending videos and other requested content

### Actual behavior

It works for a minute or 2 but continues the bug

### Screenshots/Screen recordings

Video: 

https://user-images.githubusercontent.com/89669127/184421945-41855faa-0502-4387-9c4a-a46fe520d501.mp4

### Logs

videos and loading of viewing content does noy work unless i restart wifi on my device
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=Ph53yr5arik
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.1_r1
* __OS:__ Linux motorola/minsk_t/minsk:11/RPC31.Q2-109-21-3/5ec9c:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Moto G Stylus (2021)

**Comment by Atemu** [comment] 2022-08-12 19:11
Upstream Bug.

**Comment by darlopvil** [comment] 2022-08-12 23:10
Yeap, same problem here :(

**Comment by IntoTheVoid-900** [comment] 2022-08-12 23:44
Can confirm

**Comment by JacobTravers** [comment] 2022-08-13 01:20
Looks like this was fixed upstream already:
https://github.com/TeamNewPipe/NewPipe/issues/8760

**Comment by catfromplan9** [comment] 2022-08-13 04:42
Please merge the fix from upstream

**Comment by ph00lt0** [comment] 2022-08-13 09:18
duplicate of https://github.com/polymorphicshade/NewPipe/issues/226

**Comment by ph00lt0** [comment] 2022-08-13 09:18
duplicate of https://github.com/polymorphicshade/NewPipe/issues/226

**Comment by orariley70** [comment] 2022-08-13 10:42
@catfromplan9 
I compiled the debug variant (it works, but you should really switch to normal (release) APK once the maintainer has released the new update), so your computer doesn't need to suffer like mine did.
[org.polymorphicshade.newpipe.debug.sponsorblock 0.23.2 APK.zip](https://github.com/polymorphicshade/NewPipe/files/9331241/org.polymorphicshade.newpipe.debug.sponsorblock.0.23.2.APK.zip)

**Comment by catfromplan9** [comment] 2022-08-13 15:30
> @catfromplan9 I compiled the debug variant (it works, but you should really switch to normal (release) APK once the maintainer has released the new update), so your computer doesn't need to suffer like mine did. [org.polymorphicshade.newpipe.debug.sponsorblock 0.23.2 APK.zip](https://github.com/polymorphicshade/NewPipe/files/9331241/org.polymorphicshade.newpipe.debug.sponsorblock.0.23.2.APK.zip)

Hey! Sorry I didn't mention here, but I did compile the standard newpipe updated branch. Thanks for giving me the sponsorblock one!

**Comment by polymorphicshade** [comment] 2022-08-13 15:38
@Reggie2561 please read the checklist.

**Closed by polymorphicshade** 2022-08-13 15:38 UTC
Labels: bug
