### ISSUE TITLE
Device is rebooting when playing videos with latest release

### ISSUE THREAD

**Issue by joelcieslar** [polymorphicshade/NewPipe#55] opened 2021-04-06 01:32 UTC
### Checklist

- [x] I am using the latest version - v0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Update to v0.21.0
2. Open a video
3. Press play

I just installed the latest version and now my phone sometimes reboots when trying to play a video. I've never encountered this issue before updating, but this has happened about 5 times in the last hour. It does not occur consistently so it's difficult to reproduce: sometimes videos play without any problem.

I don't have another device to record my phone with, so I am unable to offer a video for the moment.

### Actual behaviour

- Device occasionally reboots

### Expected behavior
- Video should play as expected and the device should not reboot

### Device info

 - Android version/Custom ROM version: MIUI 12.2.5
 - Device model: Xiaomi Mi 10

**Comment by joelcieslar** [comment] 2021-04-06 02:09
A little more context: I just installed the "original" NewPipe in the meantime, since my device keeps rebooting. I had no problems for a while. I took an export (settings **and** playlists) from `polymorphicshade/NewPipe` and imported it to `TeamNewPipe/NewPipe`. I started a video and the same thing happened.

It usually occurs on the second video. The first plays fine, the second one doesn't.

I will reinstall `TeamNewPipe/NewPipe` to clear my imported configuration and play with it some more to try to narrow down the cause.

**Comment by polymorphicshade** [comment] 2021-04-06 06:57
@joelcieslar this is very strange... I don't see how just the settings and playlists would cause occasional rebooting. Maybe try downloading a view and play it in the built-in local player and see if going through that process causes any reboots.

**Comment by joelcieslar** [comment] 2021-04-06 13:57
> @joelcieslar this is very strange... I don't see how just the settings and playlists would cause occasional rebooting. Maybe try downloading a view and play it in the built-in local player and see if going through that process causes any reboots.

Thanks for getting back to me (and especially thanks for your efforts with this project!)

Until now, using the local player has not caused any further reboots, but most of the time there is no audio (which is expected as it says so in the settings).

It doesn't seem to occur with a fresh install, it's seemingly just when I import my previous settings. I would surmise that something may have changed upstream in v0.21.0 which has affected one of the features I have enabled (since it happens in "vanilla" NewPipe too when I import my config).

As yet, I haven't managed to narrow it down to a particular feature/setting.

Do you know how I can open the `newpipe.settings` file that comes in the export zip file? I get garbled, partially-readable text when opening it in Visual Studio Code (says it's an unsupported encoding). It mentions `java-something-HashMap` so it seems to be a sort of "dump" of a HashMap.

Thanks again for getting back to me.

**Comment by joelcieslar** [comment] 2021-04-06 14:32
Here's what I did after (another) fresh install:

- Set SponsorBlock API to use official
- Turn on SponsorBlock
- Enable all categories of blocking
- Turn on black theme
- Turn on autoplay (always, not just Wi-Fi/cellular)

----- Seems to work fine until here -----

- Disable watch history
- Disable search history

Open a video and it will start playing. While it's playing, go back to search history. Open another video. Device reboots.

Can anyone reproduce? I'll try to narrow it down some more.

**Comment by polymorphicshade** [comment] 2021-07-26 05:05
Closed as I could not reproduce this issue.
@joelcieslar Give the latest version a try and see if are still getting reboots when trying to play videos.

**Closed by polymorphicshade** 2021-07-26 05:05 UTC
Labels: bug
