### ISSUE TITLE
Add a option to skip section marked by sponsorblock manually

### ISSUE THREAD

**Issue by Hx2-code** [polymorphicshade/NewPipe#44] opened 2021-03-05 15:46 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

An option to skip the sections of a video manually with a button like in youtube vanced would be helpful.

#### How will you/everyone benefit from this feature?

This feature would allow us to decide whether we want to skip some segments marked by sponsorblock for a particular video or not because sometimes there are some parts of a video marked by sponsorblock which I might not want to skip.

**Comment by polymorphicshade** [comment] 2021-03-05 16:40
Duplicate of #37

**Closed by polymorphicshade** 2021-03-05 16:40 UTC
Labels: enhancement
