### ISSUE TITLE
Need high playback speed upto 8x

### ISSUE THREAD

**Issue by Kladstein** [polymorphicshade/NewPipe#322] opened 2023-03-26 12:43 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The playback speed of 3x is not sufficient due to dhis need high playback speed

### Why do you want this feature?

Some peple in videos speaks very slow or sometime you need to grasp some important pointers only

### Why ist the feature relevant to this fork?

Posted this in official page but the people need this are of small percentage

**Comment by Atemu** [comment] 2023-03-26 14:53
This is not the place for stale feature requests. Please read the issue form completely.

**Comment by Kladstein** [comment] 2023-03-26 15:26
Posted this in upstream, newpipe repo but got rejected as they does not see any value in it

**Comment by Atemu** [comment] 2023-03-26 15:41
Duplicate of https://github.com/polymorphicshade/NewPipe/issues/133.

**Comment by Kladstein** [comment] 2023-03-26 16:29
That was opened 1 year ago but still the problem continues

**Comment by Atemu** [comment] 2023-03-26 16:31
Creating new issues doesn't help that.

**Comment by Kladstein** [comment] 2023-03-26 16:33
Is it really that difficult to solve this?? Can anyone provide me that feature in new fork for people

**Comment by Kladstein** [comment] 2023-03-26 16:36
Tried using libretube,skytube but in that when in high playback speed sound starts distorting, newpipe is where it is minimal

**Comment by Kladstein** [comment] 2023-03-26 16:44
Some will think that who require this insane speed yes i agree but for college kids like me and thousands more who studies some day before exam our grasping power multiples and usually a good teacher explain concepts peacefully and calmly and we just need to grasp important pointers,keywords in speech

**Comment by polymorphicshade** [comment] 2023-04-10 00:06
~~This should be requested upstream, for this feature isn't specific to my fork.~~
Edit: I just realized this is a dupe, but my comment in #133 still stands.

**Closed by polymorphicshade** 2023-04-10 00:06 UTC
Labels: enhancement
